-- 创建数据库
CREATE DATABASE db1;
CREATE DATABASE db2 CHARACTER SET utf8;
CREATE DATABASE db3 CHARACTER SET utf8 COLLATE utf8_bin;

-- 删除数据库 
DROP DATABASE db1;
DROP DATABASE db2;
DROP DATABASE db3;


-- 显示当前全部数据库
SHOW DATABASES;

-- 显示数据库创建语句
SHOW CREATE DATABASE db1;

