USE test_db;
DROP TABLE stu8;
CREATE TABLE stu8(
	id INT PRIMARY KEY,
	`name` VARCHAR(32)
);

DESC stu8;
SELECT * FROM stu8;


START TRANSACTION;

INSERT INTO stu8 VALUES(1, '张三'),(2,'李四');
SELECT * FROM stu8;

SAVEPOINT Ap;
INSERT INTO stu8 VALUES(3, '王五');
SELECT * FROM stu8;

SAVEPOINT Bp;
INSERT INTO stu8 VALUES(4, '赵六');
SELECT * FROM stu8;

ROLLBACK TO Ap;
ROLLBACK TO Bp;
ROLLBACK;
SELECT * FROM stu8;

COMMIT;


START TRANSACTION;
INSERT INTO stu8 VALUES(5, '孙七');
SAVEPOINT A;
INSERT INTO stu8 VALUES(6, '宋江');
SELECT * FROM stu8;

ROLLBACK TO A;
ROLLBACK;
COMMIT;


START TRANSACTION;
SAVEPOINT A;
SAVEPOINT B;
SAVEPOINT C;
ROLLBACK TO A;
ROLLBACK TO B;
ROLLBACK TO C;
ROLLBACK;
COMMIT;



-- 查看当前会话隔离级别
SELECT @@tx_isolation;

-- 查看当前系统隔离级别
SELECT @@global.tx_isolation;

-- 修改当前会话隔离级别
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- 修改当前系统隔离级别
SET GLOBAL TRANSACTION ISOLATION LEVEL REPEATABLE READ;